[package]
name = "rec-watchdog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
mail-send = "0.4.9"
tokio = { version = "1", features = ["full"] }
mail-builder = "0.3.2"
dotenv = "0.15"
